version: '3'

services:
  faktory:
    image: contribsys/faktory
    ports:
      - "7419:7419"
      - "7420:7420"
    environment:
      - FACTORY_WEB_UI_PASSWORD=secret
      - FACTORY_WEB_UI_USERNAME=admin
      - FACTORY_PASSWORD=secret
      - FACTORY_USERNAME=admin

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=secret


  